---
title: "Input-demand-analysis"
author: "jafshin"
date: "13/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readr)
library(ggplot2)
library(viridis)
library(sf)
library(readxl)

library(ggspatial)

```

## Reading inputs

Here I am comparing Origin and Destinations to Census Journey to work

```{r}

boundaries <- read_sf("~/ownCloud/Data/ABS_Boundaries/1270055001_sa1_2016_aust_shape/SA1_2016_AUST.shp") %>% 
  st_transform(28355)

outputDir <- "~/github/matsim-melbourne/demand/output-Sep10-10pct/"
plans <- read_csv(paste0(outputDir,"7.time/plan.csv"))
attribs <- rbind(read_csv(paste0(outputDir,"3.match/match_1.csv")),
                 read_csv(paste0(outputDir,"3.match/match_2.csv")),
                 read_csv(paste0(outputDir,"3.match/match_3.csv")),
                 read_csv(paste0(outputDir,"3.match/match_4.csv")),
                 read_csv(paste0(outputDir,"3.match/match_5.csv")))

plansWithAttrib <- plans %>% 
  left_join(attribs, by = "AgentId")

glimpse(plansWithAttrib)

```

## Activity location maps

```{r}

actLocationsSA3 <- plans %>% 
  distinct(x,y,LocationType, .keep_all = T) %>% 
  mutate(SA1_MAINCODE_2016=as.character(SA1_MAINCODE_2016)) %>% 
  left_join(st_drop_geometry(boundaries[,c("SA1_MAIN16","SA3_NAME16")]), by = c("SA1_MAINCODE_2016"="SA1_MAIN16")) %>% 
  group_by(SA3_NAME16, LocationType) %>% 
  summarise(n=n()) %>% 
  ungroup() %>% 
  mutate(n=ifelse(is.na(n), 0, n)) %>% 
  filter(!is.na(LocationType)) 
  
SA3sMap <- boundaries %>%  filter(SA3_NAME16%in%actLocationsSA3$SA3_NAME16) %>% 
  group_by(SA3_NAME16) %>% 
  summarise(geometry=st_union(geometry)) 


```

SA3 Home location

```{r}

mybreaks1 <- c(1000, 2000, 3000, 4000)

actLocationsSA3 %>% 
  filter(LocationType=="home") %>% 
  left_join(SA3sMap, by = "SA3_NAME16") %>% 
  st_as_sf() %>% 
  ggplot() +
  annotation_map_tile(type="osmgrayscale",zoom=9, alpha=0.6)+
  geom_sf(aes(fill=n ),alpha=0.8)  +
  scale_fill_viridis(option="magma", trans="sqrt", breaks=mybreaks1, name="Count" ) +
    theme_void() + 
    guides( colour = guide_legend()) +
    theme(
      legend.title =element_blank(),
      legend.position = c(0.1, 0.2),
      text = element_text(color = "#22211d"),
      plot.background = element_rect(fill = "#f5f5f2", color = NA), 
      panel.background = element_rect(fill = "#f5f5f2", color = NA), 
      legend.background = element_rect(fill = "#f5f5f2", color = NA)
    )

ggsave("~/Dropbox/Apps/Overleaf/MATSimMelbournePaper/figs/homeLocationsSA3.png",
       width = 3.5, height = 3.5)

```

SA3 work location

```{r}

mybreaks <- c(50, 200, 500, 900)

actLocationsSA3 %>% 
  filter(LocationType=="work") %>% 
  left_join(SA3sMap, by = "SA3_NAME16") %>% 
  st_as_sf() %>%
  ggplot() +
  annotation_map_tile(type="osmgrayscale",zoom=9, alpha=0.6)+
  # geom_sf(data = SA3sMap) +
  geom_sf(aes(fill=n ),alpha=0.8)  +
  # scale_color_viridis(option="magma", trans="sqrt", breaks=mybreaks, name="Work destinations" ) +
  scale_fill_viridis(option="magma", trans="sqrt", breaks=mybreaks, name="Count" ) +
  # scale_alpha_continuous(name="Work destinations", trans="sqrt", range=c(0.1, .9), breaks=mybreaks) +
  # scale_size_continuous(name="Work destinations", range=c(0.3, 8), breaks=mybreaks) +
    theme_void() + 
    guides( colour = guide_legend()) +
    theme(
      legend.title =element_blank(),
      legend.position = c(0.1, 0.2),
      text = element_text(color = "#22211d"),
      plot.background = element_rect(fill = "#f5f5f2", color = NA), 
      panel.background = element_rect(fill = "#f5f5f2", color = NA), 
      legend.background = element_rect(fill = "#f5f5f2", color = NA)
    )

ggsave("~/Dropbox/Apps/Overleaf/MATSimMelbournePaper/figs/workLocationsSA3.png",
       width = 3.5, height = 3.5)

```


SA3 Education map


```{r}

mybreaks <- c(50, 100, 200)

actLocationsSA3 %>% 
  filter(LocationType=="education") %>% 
  left_join(SA3sMap, by = "SA3_NAME16") %>% 
  st_as_sf() %>%
  ggplot() +
  annotation_map_tile(type="osmgrayscale",zoom=9, alpha=0.6)+
  # geom_sf(data = SA3sMap) +
  geom_sf(aes(fill=n ),alpha=0.8)  +
  # scale_color_viridis(option="magma", trans="sqrt", breaks=mybreaks, name="Work destinations" ) +
  scale_fill_viridis(option="magma", trans="sqrt", breaks=mybreaks) +
  # scale_alpha_continuous(name="Work destinations", trans="sqrt", range=c(0.1, .9), breaks=mybreaks) +
  # scale_size_continuous(name="Work destinations", range=c(0.3, 8), breaks=mybreaks) +
    theme_void() + 
    guides( colour = guide_legend()) +
    theme(
      legend.title =element_blank(),
      legend.position = c(0.1, 0.2),
      text = element_text(color = "#22211d"),
      plot.background = element_rect(fill = "#f5f5f2", color = NA), 
      panel.background = element_rect(fill = "#f5f5f2", color = NA), 
      legend.background = element_rect(fill = "#f5f5f2", color = NA)
    )

ggsave("~/Dropbox/Apps/Overleaf/MATSimMelbournePaper/figs/educationLocationsSA3.png",
       width = 3.5, height = 3.5)

```


SA3 park map

```{r}

mybreaks <- c(50, 250, 500)

actLocationsSA3 %>% 
  filter(LocationType=="park") %>% 
  left_join(SA3sMap, by = "SA3_NAME16") %>% 
  st_as_sf() %>%
  ggplot() +
  annotation_map_tile(type="osmgrayscale",zoom=9, alpha=0.6)+
  # geom_sf(data = SA3sMap) +
  geom_sf(aes(fill=n ),alpha=0.8)  +
  # scale_color_viridis(option="magma", trans="sqrt", breaks=mybreaks, name="Work destinations" ) +
  scale_fill_viridis(option="magma", trans="sqrt", breaks=mybreaks) +
  # scale_alpha_continuous(name="Work destinations", trans="sqrt", range=c(0.1, .9), breaks=mybreaks) +
  # scale_size_continuous(name="Work destinations", range=c(0.3, 8), breaks=mybreaks) +
    theme_void() + 
    guides( colour = guide_legend()) +
    theme(
      legend.title =element_blank(),
      legend.position = c(0.1, 0.2),
      text = element_text(color = "#22211d"),
      plot.background = element_rect(fill = "#f5f5f2", color = NA), 
      panel.background = element_rect(fill = "#f5f5f2", color = NA), 
      legend.background = element_rect(fill = "#f5f5f2", color = NA)
    )

ggsave("~/Dropbox/Apps/Overleaf/MATSimMelbournePaper/figs/parkLocationsSA3.png",
       width = 3.5, height = 3.5)

```


SA3 commercial map


```{r}

mybreaks <- c(50, 350, 850)

actLocationsSA3 %>% 
  filter(LocationType=="commercial") %>% 
  left_join(SA3sMap, by = "SA3_NAME16") %>% 
  st_as_sf() %>%
  ggplot() +
  annotation_map_tile(type="osmgrayscale",zoom=9, alpha=0.6)+
  # geom_sf(data = SA3sMap) +
  geom_sf(aes(fill=n ),alpha=0.8)  +
  # scale_color_viridis(option="magma", trans="sqrt", breaks=mybreaks, name="Work destinations" ) +
  scale_fill_viridis(option="magma", trans="sqrt", breaks=mybreaks) +
  # scale_alpha_continuous(name="Work destinations", trans="sqrt", range=c(0.1, .9), breaks=mybreaks) +
  # scale_size_continuous(name="Work destinations", range=c(0.3, 8), breaks=mybreaks) +
    theme_void() + 
    guides( colour = guide_legend()) +
    theme(
      legend.title =element_blank(),
      legend.position = c(0.1, 0.2),
      text = element_text(color = "#22211d"),
      plot.background = element_rect(fill = "#f5f5f2", color = NA), 
      panel.background = element_rect(fill = "#f5f5f2", color = NA), 
      legend.background = element_rect(fill = "#f5f5f2", color = NA)
    )

ggsave("~/Dropbox/Apps/Overleaf/MATSimMelbournePaper/figs/commercialLocationsSA3.png",
       width = 3.5, height = 3.5)

```



## Trips to work OD analysis

Selecting the work trips

```{r}
tripsToWork <- plansWithAttrib %>% 
  filter(lag(Activity=="Home") & Activity=="Work")%>% 
  distinct(AgentId, .keep_all=T)

glimpse(tripsToWork)
```

## OD analysis

Aggregating ODs at SA3

```{r}

boundariesSA2 <- st_drop_geometry(boundaries[,c("SA2_MAIN16","SA3_NAME16")]) %>% 
  distinct()

agentHomes <- plansWithAttrib %>% 
  filter(Activity=="Home") %>% 
  mutate(HomeSA2=as.character(SA2_MAINCODE)) %>% 
  dplyr::select(AgentId, HomeSA2) %>% 
  distinct(AgentId, .keep_all=T)

tripsToWorkSA3 <- tripsToWork %>%       
  # mutate(GEOMETRY=paste0("POINT(",x," ",y,")")) %>%
  # st_as_sf(wkt = "GEOMETRY", crs = 28355) %>% 
  # st_join(boundaries)
  mutate(SA1_MAINCODE_2016.x=as.character(SA1_MAINCODE_2016.x)) %>% 
  left_join(st_drop_geometry(boundaries[,c("SA1_MAIN16","SA3_NAME16")]), by = c("SA1_MAINCODE_2016.x"="SA1_MAIN16")) %>% 
  rename("DestinationSA3"="SA3_NAME16") %>% 
  left_join(agentHomes, by="AgentId") %>% 
  left_join(boundariesSA2, by = c("HomeSA2"="SA2_MAIN16")) %>% 
  rename("HomeSA3"="SA3_NAME16")  %>% 
  group_by(HomeSA3,DestinationSA3)  %>% 
  summarise(numTrips=n()) %>% 
  mutate(DemandTripPerHomeSA3=10*numTrips) %>%
  mutate(DemandTripPctPerHomeSA3=100*numTrips/sum(numTrips)) %>%
  dplyr::select(-numTrips) %>% 
  ungroup()
  
ODPairs <- tripsToWorkSA3 %>% 
  transmute(pairs=paste0(HomeSA3,"_",DestinationSA3))

tripsToWorkSA3 %>% glimpse()
# tripsToWorkSA3 %>% filter(HomeSA3==DestinationSA3)
tripsToWorkSA3$DemandTripPerHomeSA3 %>% sum()
```


```{r}
censusOd <- read_csv("~/ownCloud/Data/ABS_Census/SA3 (UR) and SA3 (POW).csv", skip=9) %>% 
  rename(HomeSA3=`SA3 (UR)`, DestinationSA3=`SA3 (POW)`) %>% 
  dplyr::select(-Counting, -X5)  %>%
  filter(HomeSA3!="Total" & DestinationSA3!="Total") %>% 
  filter(paste0(HomeSA3,"_",DestinationSA3) %in% ODPairs$pairs) %>%  
  
  # filter(HomeSA3%in%tripsToWorkSA3$HomeSA3) %>% 
  # filter(DestinationSA3%in%tripsToWorkSA3$DestinationSA3) %>% 
  group_by(HomeSA3) %>% 
  # mutate(numTrips=sum(Count)) %>%
  mutate(CensusTripPctPerHomeSA3=100*Count/sum(Count)) %>%
  mutate(CensusTripPerHomeSA3=Count) %>%
  dplyr::select(-Count)

censusOd %>% glimpse()
censusOd$CensusTripPerHomeSA3 %>% sum()
```

Joining the two together

```{r}

ODPcts <- tripsToWorkSA3 %>% 
  left_join(censusOd, by = c("HomeSA3","DestinationSA3")) 

ODPcts %>% 
  ggplot(aes(x = CensusTripPctPerHomeSA3, y= DemandTripPctPerHomeSA3))+
  geom_point() + scale_x_continuous(trans='log2') +
  scale_y_continuous(trans='log2')

```

```{r}
ODError <- tripsToWorkSA3 %>% 
  # filter(DemandTripPctPerHomeSA3>1) %>% # I need to look into this
  left_join(censusOd, by = c("HomeSA3","DestinationSA3")) %>%  
  filter(CensusTripPctPerHomeSA3>1 | DemandTripPctPerHomeSA3>1) %>% # I need to look into this
  # filter(HomeSA3!="Stonnington - West" & DestinationSA3!="Manningham - East") %>% 
  mutate(deltaSq=abs(DemandTripPctPerHomeSA3-CensusTripPctPerHomeSA3)/CensusTripPctPerHomeSA3) %>% 
  group_by(HomeSA3) %>%
  # summarise(n=n())
  summarise(n=n(),mape=(100/n)*(sum(deltaSq))) 


ODError$HomeSA3 <- factor(ODError$HomeSA3, levels = ODError$HomeSA3[order(ODError$mape)])
ODError %>% 
  arrange(desc(mape)) %>% 
  ggplot(aes(x=mape,y=HomeSA3, fill=mape)) +
  geom_col() +
  scale_fill_viridis_c()

```


```{r}

SA3sMap <- boundaries %>% filter(SA3_NAME16%in%tripsToWorkSA3$HomeSA3) %>% 
  group_by(SA3_NAME16) %>% 
  summarise(geometry=st_union(geometry)) 

SA3sMap %>% 
  left_join(ODError, by=c("SA3_NAME16"="HomeSA3")) %>% 
  ggplot() +
  annotation_map_tile(type="osmgrayscale",zoom=9) +
  geom_sf(aes(fill = mape), alpha=0.8) +
  scale_fill_viridis_c(option="magma", trans = "sqrt", name= "MAPE") 

ggsave("~/Dropbox/Apps/Overleaf/MATSimMelbournePaper/figs/od-mape.png")

```


# WAPE


```{r}
ODError2 <- tripsToWorkSA3 %>% 
  # filter(DemandTripPctPerHomeSA3>1) %>% # I need to look into this
  left_join(censusOd, by = c("HomeSA3","DestinationSA3")) %>%  
  # filter(CensusTripPctPerHomeSA3>1 | DemandTripPctPerHomeSA3>1) %>% # I need to look into this
  # filter(HomeSA3!="Stonnington - West" & DestinationSA3!="Manningham - East") %>% 
  mutate(delta=abs(DemandTripPerHomeSA3-CensusTripPerHomeSA3)) %>% 
  group_by(HomeSA3) %>%
  summarise(n=n(),wape=(sum(delta)/sum(CensusTripPerHomeSA3))) 
  

ODError2$HomeSA3 <- factor(ODError2$HomeSA3, levels = ODError2$HomeSA3[order(ODError2$wape)])
ODError2 %>% 
  arrange(desc(wape)) %>% 
  ggplot(aes(x=wape,y=HomeSA3, fill=wape)) +
  geom_col() +
  scale_fill_viridis_c()

```


```{r}
SA3sMap <- boundaries %>% filter(SA3_NAME16%in%tripsToWorkSA3$HomeSA3) %>% 
  group_by(SA3_NAME16) %>% 
  summarise(geometry=st_union(geometry)) 

SA3sMap %>% 
  left_join(ODError2, by=c("SA3_NAME16"="HomeSA3")) %>% 
  ggplot() +
  annotation_map_tile(type="osmgrayscale",zoom=9) +
  geom_sf(aes(fill = wape), alpha=0.8) +
  scale_fill_viridis_c(option="magma", trans = "sqrt", name= "WAPE") 

ggsave("~/Dropbox/Apps/Overleaf/MATSimMelbournePaper/figs/od-wape.png")
```

## Home trips count

```{r}

tripsToWorkSA3 %>% 
  # filter(DemandTripPctPerHomeSA3>1) %>% # I need to look into this
  left_join(censusOd, by = c("HomeSA3","DestinationSA3")) %>% 
  group_by(HomeSA3) %>% 
  summarise(censusHomeSa3=sum(CensusTripPerHomeSA3),
            demandHomeSa3=sum(DemandTripPerHomeSA3))

```


