---
title: "observation-preparation"
author: "jafshin"
date: "14/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Car traffic data

### Car traffic data cleaning 

Reading input 

```{r}
###############################################################################
# Day of Week where 1=Monday, 2=Tuesday,3=Wednesday,                          #
# 4=Thursday,5=Friday,6=Saturday and 7=Sunday                                 #
###############################################################################
# A=Actual count, Ehis=Estimate based on historic data,                       #
# Egmr=Estimate based on global substitution, Erte=Estimate based on route    #
###############################################################################

carData <- read_csv("~/ownCloud/io.github.jafshin/calibration-validation/data/observations/TYPICAL_HOURLY_VOLUME_DATA.csv")

carDataFiltered <- carData %>% 
  filter(PERIOD_TYPE=="SCHOOL TERM/NORMAL") %>% 
  filter(DOW==3) %>% 
  # Filter to those with high enough number traffic
  mutate(HMGNS_FLOW_ID=as.character(HMGNS_FLOW_ID)) %>% 
  mutate(HMGNS_LNK_ID=as.character(HMGNS_LNK_ID)) %>% 
  dplyr::select(-DOW) %>% 
  mutate(totalVol=rowSums(across(where(is.numeric)))) 

# carDataFilter %>% distinct(HMGNS_FLOW_ID) %>% arrange(HMGNS_FLOW_ID)
```

Adding geometry to the roads

```{r}
# TIS_ROUTE_FLOW=	Traffic Information Route Flow (1=Generally out of Melb, Generally 0= into Melb)
# 

# HMGNS_FLOW_ID	Text	10	Homogeneous flow id eg 1234. An internal reference for Homogenous Flow. Homogeneous flow - The traffic volume information associated with the traffic flow along a link that is representative of all travel along the whole link

# ROAD_NBR	Number	8	ROAD_NUMBER

htvnData <- st_read("~/ownCloud/io.github.jafshin/calibration-validation/data/observations/homogenous_traffic_flow-shp/3ad2d9d5-dd49-40bf-86c4-ccf114d2e4582020328-1-cs85vw.3kgy7.shp") %>% 
  st_transform(28355) %>% 
  mutate(HMGNS_FLOW_ID=as.character(HMGNS_FLOW))

# glimpse(htvnData)

# htvnData %>% distinct(HMGNS_FLOW) %>% arrange(HMGNS_FLOW)

carDataJoined <- carDataFiltered %>%
  left_join(htvnData, by="HMGNS_FLOW_ID") %>% 
  st_as_sf()

st_write(carDataJoined, "carDataJoined.sqlite", delete_dsn = T)
```

Crop to greater Melbourne

```{r}
gMelbBoundary <- st_read("~/ownCloud/Data/ABS_Boundaries/GreaterMelbourneArea/GMEL_SA4_2016_Polygons.sqlite")  %>% 
  st_transform(28355)
  
carDataCroped <- carDataJoined %>% 
  st_intersection(gMelbBoundary)

st_write(carDataCroped, "carDataCropedSmall.sqlite", delete_dsn = T)
```

### AM Peak data

```{r}

amCarData <- carDataCroped %>% 
  filter(TIS_ROUTE1==0)

```

finding high volume AM roads

```{r}

amHighVolRoads <- amCarData %>% 
  st_drop_geometry() %>% 
  group_by(ROAD_NBR) %>% 
  summarise(roadVol=mean(totalVol)) %>% 
  slice_max(order_by = roadVol, prop=0.1)

amHighVolCarData <- amCarData %>% 
  filter(ROAD_NBR %in% amHighVolRoads$ROAD_NBR) %>% 
  group_by(ROAD_NBR) %>% 
  slice_max(order_by = totalVol, n=1)

st_write(amHighVolCarData, "amHighVolCarData.sqlite", delete_dsn = T)
```



### PM Peak data

```{r}

pmCarData <- carDataCroped %>% 
  filter(TIS_ROUTE1==1)

```

finding high volume AM roads

```{r}

pmHighVolRoads <- pmCarData %>% 
  st_drop_geometry() %>% 
  group_by(ROAD_NBR) %>% 
  summarise(roadVol=mean(totalVol)) %>% 
  slice_max(order_by = roadVol, prop=0.1)

pmHighVolCarData <- pmCarData %>% 
  filter(ROAD_NBR %in% pmHighVolRoads$ROAD_NBR) %>% 
  group_by(ROAD_NBR) %>% 
  slice_max(order_by = totalVol, n=1)

st_write(pmHighVolCarData, "pmHighVolCarData.sqlite", delete_dsn = T)
```

