---
title: "mode-share-comparison"
author: "jafshin"
date: "05/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


# Trip comparison

```{r, preparing the trip data}

# Simulation output ------------
simOutputTrips <- read_delim(gzfile("output_trips.csv.gz"),
                      delim=";") %>% 
  # Removing trips with zero distance
  filter(traveled_distance>0) %>%   
  # filter(longest_distance_mode!="walk") %>% 
  mutate(longest_distance_mode=ifelse(longest_distance_mode=="netwalk", "walk", longest_distance_mode)) 

vista_trips_cleaned <- 
  read_csv("~/ownCloud/Data/VISTA/2012-18/T_VISTA1218_V1.csv") %>% 
  # filterting to 16-18
  filter(grepl('Y16|Y17|Y18',HHID)) %>%
  # Filtering to valid trips
  filter(CUMDIST>0) %>% 
  # Refactoring the linkmode in VISTA
  mutate(mode=case_when(LINKMODE=="Bicycle" ~ "bike",
                        LINKMODE=="Vehicle Driver" ~ "car", 
                        LINKMODE=="Walking" ~ "walk",
                        LINKMODE%in%c("Public Bus","Train","Tram") ~ "pt",
                        TRUE ~ "other")) %>% 
  # Filtering out modes==other
  filter(mode!="other") 

```

## Work trips comparison

```{r}

sim_work_trips <- simOutputTrips %>% filter(end_activity_type=="Work")

vista_work_trip <- vista_trips_cleaned %>% filter(DESTPLACE1=="Workplace")

sim_work_trips %>% count(mode=longest_distance_mode) %>% mutate(sim_pct=100*n/sum(n)) %>% 
  left_join({ vista_work_trip %>% count(mode) %>% mutate(vista_pct=100*n/sum(n))}, by="mode") 

```

## Non-work trips comparison

```{r}

sim_nonwork_trips <- simOutputTrips %>% filter(end_activity_type!="Work")

vista_nonwork_trip <- vista_trips_cleaned %>% filter(DESTPLACE1!="Workplace")

sim_nonwork_trips %>% count(mode=longest_distance_mode) %>% mutate(sim_pct=100*n/sum(n)) %>% 
  left_join({ vista_nonwork_trip %>% count(mode) %>% mutate(vista_pct=100*n/sum(n))}, by="mode") 

```

# Tour-based comparison

```{r, preparing the tour data (this might take a while)}

source("../etc/find-tours.R")

# Find tour mode and distance

## Simulation output ---------------

simOutputTrips <- read_delim(gzfile("output_trips.csv.gz"), delim=";") %>% 
  # Removing trips with zero distance
  filter(traveled_distance>0) %>%   
  # filter(longest_distance_mode!="walk") %>% 
  mutate(longest_distance_mode=ifelse(longest_distance_mode=="netwalk", 
                                      "walk", longest_distance_mode)) 

simulation_output_tours <- find_matsim_tours(simOutputTrips)

sim_tours <- simulation_output_tours %>% 
  mutate(traveled_distance=traveled_distance/1000) %>% 
  left_join(simOutputTrips[,c("person", "trip_number", "trip_id", "longest_distance_mode")],
            by = c("person", "trip_number"))  

sim_tours_max_dist <- sim_tours %>%
  mutate(traveled_distance=traveled_distance/1000) %>% 
  group_by(tour_id) %>% 
  summarise(max_dist = max(traveled_distance), tour_dist=sum(traveled_distance))

sim_tours_max_mode <- sim_tours %>%
  group_by(tour_id, longest_distance_mode) %>% 
  summarise(mode_dist=sum(traveled_distance)) %>%
  filter(mode_dist==max(mode_dist))

sim_tours_added <- sim_tours %>% 
  distinct(tour_id) %>% 
  left_join(sim_tours_max_dist, by ="tour_id") %>% 
  left_join(sim_tours_max_mode, by ="tour_id") 

## VISTA ----------------

vista_trips_cleaned <- 
  read_csv("~/ownCloud/Data/VISTA/2012-18/T_VISTA1218_V1.csv") %>% 
  # filterting to 16-18
  filter(grepl('Y16|Y17|Y18',HHID)) %>%
  # Filtering to valid trips
  filter(CUMDIST>0) %>% 
  # Refactoring the linkmode in VISTA
  mutate(mode=case_when(LINKMODE=="Bicycle" ~ "bike",
                        LINKMODE=="Vehicle Driver" ~ "car", 
                        LINKMODE=="Walking" ~ "walk",
                        LINKMODE%in%c("Public Bus","Train","Tram") ~ "pt",
                        TRUE ~ "other")) %>% 
  # Filtering out modes==other
  filter(mode!="other") 


vista_trips_tours <- find_vista_tours(vista_trips_cleaned)

vista_tours <- vista_trips_tours %>%  
  mutate(mode=case_when(modes=="Bicycle" ~ "bike",
                        modes=="Vehicle Driver" ~ "car", 
                        modes=="Walking" ~ "walk",
                        modes%in%c("Public Bus","Train","Tram") ~ "pt",
                        TRUE ~ "other"))

vista_tours_max_dist <- vista_tours %>% 
  group_by(tour_id) %>% 
  summarise(max_dist = max(traveled_distance), tour_dist=sum(traveled_distance))


vista_tours_max_mode <- vista_tours %>%
  group_by(tour_id, mode) %>% 
  summarise(mode_dist=sum(traveled_distance)) %>%
  filter(mode_dist==max(mode_dist))


vista_tours_added <- vista_tours %>% 
  distinct(tour_id) %>% 
  left_join(vista_tours_max_dist, by ="tour_id") %>% 
  left_join(vista_tours_max_mode, by ="tour_id") 


```


```{r, compare tour mode shares all tours}

vista_tours_added %>% count(mode) %>% mutate(pct_vista=100*n/sum(n)) %>% 
  left_join({sim_tours_added %>% count(mode=longest_distance_mode) %>% mutate(pct_sim=100*n/sum(n))}, by = "mode")
```

```{r Census JTW}

censusJTW <- read_csv("~/ownCloud/Data/ABS_Census/SA3 (UR) and MTW15P Method of Travel to Work (15 travel modes).csv", 
                        skip=9, ) %>%
  rename(HomeSA3=`SA3 (UR)`,
         MTW=`MTW15P Method of Travel to Work (15 travel modes)`) %>%
  dplyr::select(HomeSA3, MTW, Count) %>%
  filter(!is.na(MTW)) %>% 
  filter(MTW!="Total") %>% 
  # filter(HomeSA3 %in% unique(HomeSA3)) %>% 
  mutate(mode=case_when(MTW=="Bicycle" ~ "bicycle",
                        MTW%in%c("Car, as driver") ~ "car", # Not including ,"Car, as passenger"
                        MTW%in%c("Bus","Train", "Tram") ~ "pt",
                        MTW=="Walked only" ~ "walk",
                        TRUE ~ "other")) %>% 
  filter(mode!="other") 



censusJTWCounted <- censusJTW %>% 
  group_by(mode) %>% 
  summarise(n=sum(Count)) %>% 
  mutate(pct=100*n/sum(n)) %>% 
  dplyr::select(mode, n, pct)

censusJTWCounted
```
